apiVersion: apps/v1
kind: Deployment
metadata:
  name: databasedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      containers:
      - name: appdb-container
        image: skiddie/mysql:v1.0
        volumeMounts:
          - name: app-db-data
            mountPath: /var/lib/mysql
        ports:
        - name: db-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes: 
        - name: app-db-data
          awsElasticBlockStore:
            volumeID: vol-023eae3fe89114a0f
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox
          args: ["rm", "-rf", "/var/lib/mysql/*"]
          volumeMounts:
          - name: app-db-data
            mountPath: /var/lib/mysql
