apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      labels:
        app: tomcatapp
    spec:
      containers:
      - name: tomcatapp-container
        image: skiddie/tomcatapp:v1.0
        ports:
        - containerPort: 8080
      initContainers:
        - name: db-init
          image: busybox:latest
          args: ['sh', '-c', 'until nslookup db01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 2; done;']
        - name: mem-init
          image: busybox:latest
          args: ['sh', '-c', 'until nslookup mc01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcached; sleep 2; done;']
